
package edu.cs751homework4.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OrderServiceImplServicePortType", targetNamespace = "http://service.cs751homework4.edu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OrderServiceImplServicePortType {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addOrder", targetNamespace = "http://service.cs751homework4.edu/", className = "edu.cs751homework4.service.AddOrder")
    @ResponseWrapper(localName = "addOrderResponse", targetNamespace = "http://service.cs751homework4.edu/", className = "edu.cs751homework4.service.AddOrderResponse")
    public boolean addOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        Order arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteOrder", targetNamespace = "http://service.cs751homework4.edu/", className = "edu.cs751homework4.service.DeleteOrder")
    @ResponseWrapper(localName = "deleteOrderResponse", targetNamespace = "http://service.cs751homework4.edu/", className = "edu.cs751homework4.service.DeleteOrderResponse")
    public boolean deleteOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<edu.cs751homework4.service.Order>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOrders", targetNamespace = "http://service.cs751homework4.edu/", className = "edu.cs751homework4.service.GetOrders")
    @ResponseWrapper(localName = "getOrdersResponse", targetNamespace = "http://service.cs751homework4.edu/", className = "edu.cs751homework4.service.GetOrdersResponse")
    public List<Order> getOrders();

    /**
     * 
     * @param arg0
     * @return
     *     returns edu.cs751homework4.service.Order
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOrder", targetNamespace = "http://service.cs751homework4.edu/", className = "edu.cs751homework4.service.GetOrder")
    @ResponseWrapper(localName = "getOrderResponse", targetNamespace = "http://service.cs751homework4.edu/", className = "edu.cs751homework4.service.GetOrderResponse")
    public Order getOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateOrder", targetNamespace = "http://service.cs751homework4.edu/", className = "edu.cs751homework4.service.UpdateOrder")
    @ResponseWrapper(localName = "updateOrderResponse", targetNamespace = "http://service.cs751homework4.edu/", className = "edu.cs751homework4.service.UpdateOrderResponse")
    public boolean updateOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Item arg1);

}
