package com.guitariffic.dao.fakesheet.adapter;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.OutputStream;
import java.util.Vector;

import org.docx4j.convert.out.html.AbstractHtmlExporter;
import org.docx4j.convert.out.html.HtmlExporterNG2;
import org.docx4j.openpackaging.packages.WordprocessingMLPackage;

import com.guitariffic.dao.fakesheet.BaseAdapter;
import com.guitariffic.model.FakeSheet;
import com.guitariffic.model.GuitarChordChart;

/**
 * Simple HTML adapter for fake sheet.
 * 
 * @author ryszardkilarski
 * 
 */
public class HTMLAdapter extends BaseAdapter
{

	public Object openFile(File file) throws IOException, ClassNotFoundException
	{
		return null;
	}

	/**
	 * Write object as an HTML file.
	 */
	@SuppressWarnings("deprecation")
	public void saveFile(Object o, File file) throws IOException
	{
		DOCX4JAdapter documentGetter = new DOCX4JAdapter();
		WordprocessingMLPackage wordMLPackage = documentGetter.generateDocument((FakeSheet) o);

		AbstractHtmlExporter exporter = new HtmlExporterNG2();

		// Write to StreamResult (in this case, an output stream)
		OutputStream os = new java.io.FileOutputStream(file.getAbsolutePath() + ".html");
		javax.xml.transform.stream.StreamResult result = new javax.xml.transform.stream.StreamResult(os);
		try
		{
			exporter.html(wordMLPackage, result, file.getCanonicalPath() + "_files");
		} catch (Exception e)
		{
			e.printStackTrace();
		}
		return;
	}

	@SuppressWarnings("unused")
	private void saveFile2(Object o, File file) throws IOException
	{
		FakeSheet fakeSheet = (FakeSheet) o;
		String[] textArray;
		Vector<Vector<GuitarChordChart>> chordCharts;
		String fileDirectory = file.getParent() + "/" + file.getName().replace(".html", "") + "_files";
		String fileLocalPath = file.getName().replace(".html", "") + "_files";

		BufferedWriter bw = new BufferedWriter(new FileWriter(file));

		write("<html xmlns:v=\"urn:schemas-microsoft-com:vml\"", bw);
		write("xmlns:o=\"urn:schemas-microsoft-com:office:office\"", bw);
		write("xmlns:w=\"urn:schemas-microsoft-com:office:word\"", bw);
		write("xmlns:m=\"http://schemas.microsoft.com/office/2004/12/omml\"", bw);
		write("xmlns=\"http://www.w3.org/TR/REC-html40\">", bw);
		write("", bw);
		write("<head>", bw);
		write("<meta http-equiv=Content-Type content=\"text/html; charset=windows-1252\">", bw);
		write("<meta name=ProgId content=Word.Document>", bw);
		write("<meta name=Generator content=\"Microsoft Word 14\">", bw);
		write("<meta name=Originator content=\"Microsoft Word 14\">", bw);
		// write("<link rel=File-List href=\"Layla_files/filelist.xml\">",bw);
		// write("<link rel=Edit-Time-Data href=\"Layla_files/editdata.mso\">",bw);
		write("<!--[if !mso]>", bw);
		write("<style>", bw);
		write("v\\:* {behavior:url(#default#VML,bw);}", bw);
		write("o\\:* {behavior:url(#default#VML,bw);}", bw);
		write("w\\:* {behavior:url(#default#VML,bw);}", bw);
		write(".shape {behavior:url(#default#VML,bw);}", bw);
		write("</style>", bw);
		write("<![endif]--><!--[if gte mso 9]><xml>", bw);
		write(" <o:DocumentProperties>", bw);
		write("  <o:Author>Ryszard Kilarski</o:Author>", bw);
		write("  <o:LastAuthor>Ryszard Kilarski</o:LastAuthor>", bw);
		write("  <o:Revision>2</o:Revision>", bw);
		write("  <o:TotalTime>1</o:TotalTime>", bw);
		write("  <o:Created>2011-11-10T19:01:00Z</o:Created>", bw);
		write("  <o:LastSaved>2011-11-10T19:01:00Z</o:LastSaved>", bw);
		write("  <o:Pages>1</o:Pages>", bw);
		write("  <o:Words>180</o:Words>", bw);
		write("  <o:Characters>1026</o:Characters>", bw);
		write("  <o:Lines>8</o:Lines>", bw);
		write("  <o:Paragraphs>2</o:Paragraphs>", bw);
		write("  <o:CharactersWithSpaces>1204</o:CharactersWithSpaces>", bw);
		write("  <o:Version>14.00</o:Version>", bw);
		write(" </o:DocumentProperties>", bw);
		write("</xml><![endif]-->", bw);
		// write("<link rel=themeData href=\"Layla_files/themedata.thmx\">",bw);
		// write("<link rel=colorSchemeMapping href=\"Layla_files/colorschememapping.xml\">",bw);
		write("<!--[if gte mso 9]><xml>", bw);
		write(" <w:WordDocument>", bw);
		write("  <w:SpellingState>Clean</w:SpellingState>", bw);
		write("  <w:GrammarState>Clean</w:GrammarState>", bw);
		write("  <w:TrackMoves>false</w:TrackMoves>", bw);
		write("  <w:TrackFormatting/>", bw);
		write("  <w:PunctuationKerning/>", bw);
		write("  <w:DrawingGridHorizontalSpacing>6 pt</w:DrawingGridHorizontalSpacing>", bw);
		write("  <w:DisplayHorizontalDrawingGridEvery>2</w:DisplayHorizontalDrawingGridEvery>", bw);
		write("  <w:ValidateAgainstSchemas/>", bw);
		write("  <w:SaveIfXMLInvalid>false</w:SaveIfXMLInvalid>", bw);
		write("  <w:IgnoreMixedContent>false</w:IgnoreMixedContent>", bw);
		write("  <w:AlwaysShowPlaceholderText>false</w:AlwaysShowPlaceholderText>", bw);
		write("  <w:DoNotPromoteQF/>", bw);
		write("  <w:LidThemeOther>EN-US</w:LidThemeOther>", bw);
		write("  <w:LidThemeAsian>X-NONE</w:LidThemeAsian>", bw);
		write("  <w:LidThemeComplexScript>X-NONE</w:LidThemeComplexScript>", bw);
		write("  <w:Compatibility>", bw);
		write("   <w:BreakWrappedTables/>", bw);
		write("   <w:SnapToGridInCell/>", bw);
		write("   <w:WrapTextWithPunct/>", bw);
		write("   <w:UseAsianBreakRules/>", bw);
		write("   <w:DontGrowAutofit/>", bw);
		write("   <w:SplitPgBreakAndParaMark/>", bw);
		write("   <w:EnableOpenTypeKerning/>", bw);
		write("   <w:DontFlipMirrorIndents/>", bw);
		write("   <w:OverrideTableStyleHps/>", bw);
		write("  </w:Compatibility>", bw);
		write("  <m:mathPr>", bw);
		write("   <m:mathFont m:val=\"Cambria Math\"/>", bw);
		write("   <m:brkBin m:val=\"before\"/>", bw);
		write("   <m:brkBinSub m:val=\"&#45;-\"/>", bw);
		write("   <m:smallFrac m:val=\"off\"/>", bw);
		write("   <m:dispDef/>", bw);
		write("   <m:lMargin m:val=\"0\"/>", bw);
		write("   <m:rMargin m:val=\"0\"/>", bw);
		write("   <m:defJc m:val=\"centerGroup\"/>", bw);
		write("   <m:wrapIndent m:val=\"1440\"/>", bw);
		write("   <m:intLim m:val=\"subSup\"/>", bw);
		write("   <m:naryLim m:val=\"undOvr\"/>", bw);
		write("  </m:mathPr></w:WordDocument>", bw);
		write("</xml><![endif]--><!--[if gte mso 9]><xml>", bw);
		write(" <w:LatentStyles DefLockedState=\"false\" DefUnhideWhenUsed=\"true\"", bw);
		write("  DefSemiHidden=\"true\" DefQFormat=\"false\" DefPriority=\"99\"", bw);
		write("  LatentStyleCount=\"267\">", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"0\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" QFormat=\"true\" Name=\"Normal\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"9\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" QFormat=\"true\" Name=\"heading 1\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"9\" QFormat=\"true\" Name=\"heading 2\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"9\" QFormat=\"true\" Name=\"heading 3\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"9\" QFormat=\"true\" Name=\"heading 4\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"9\" QFormat=\"true\" Name=\"heading 5\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"9\" QFormat=\"true\" Name=\"heading 6\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"9\" QFormat=\"true\" Name=\"heading 7\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"9\" QFormat=\"true\" Name=\"heading 8\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"9\" QFormat=\"true\" Name=\"heading 9\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"39\" Name=\"toc 1\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"39\" Name=\"toc 2\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"39\" Name=\"toc 3\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"39\" Name=\"toc 4\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"39\" Name=\"toc 5\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"39\" Name=\"toc 6\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"39\" Name=\"toc 7\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"39\" Name=\"toc 8\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"39\" Name=\"toc 9\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"35\" QFormat=\"true\" Name=\"caption\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"10\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" QFormat=\"true\" Name=\"Title\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"1\" Name=\"Default Paragraph Font\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"11\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" QFormat=\"true\" Name=\"Subtitle\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"0\" Name=\"Hyperlink\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"22\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" QFormat=\"true\" Name=\"Strong\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"20\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" QFormat=\"true\" Name=\"Emphasis\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"0\" Name=\"HTML Preformatted\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"0\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Table Grid\"/>", bw);
		write("  <w:LsdException Locked=\"false\" UnhideWhenUsed=\"false\" Name=\"Placeholder Text\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"1\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" QFormat=\"true\" Name=\"No Spacing\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"60\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Light Shading\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"61\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Light List\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"62\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Light Grid\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"63\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Medium Shading 1\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"64\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Medium Shading 2\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"65\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Medium List 1\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"66\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Medium List 2\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"67\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Medium Grid 1\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"68\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Medium Grid 2\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"69\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Medium Grid 3\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"70\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Dark List\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"71\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Colorful Shading\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"72\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Colorful List\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"73\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Colorful Grid\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"60\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Light Shading Accent 1\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"61\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Light List Accent 1\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"62\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Light Grid Accent 1\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"63\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Medium Shading 1 Accent 1\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"64\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Medium Shading 2 Accent 1\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"65\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Medium List 1 Accent 1\"/>", bw);
		write("  <w:LsdException Locked=\"false\" UnhideWhenUsed=\"false\" Name=\"Revision\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"34\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" QFormat=\"true\" Name=\"List Paragraph\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"29\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" QFormat=\"true\" Name=\"Quote\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"30\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" QFormat=\"true\" Name=\"Intense Quote\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"66\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Medium List 2 Accent 1\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"67\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Medium Grid 1 Accent 1\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"68\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Medium Grid 2 Accent 1\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"69\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Medium Grid 3 Accent 1\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"70\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Dark List Accent 1\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"71\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Colorful Shading Accent 1\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"72\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Colorful List Accent 1\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"73\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Colorful Grid Accent 1\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"60\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Light Shading Accent 2\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"61\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Light List Accent 2\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"62\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Light Grid Accent 2\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"63\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Medium Shading 1 Accent 2\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"64\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Medium Shading 2 Accent 2\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"65\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Medium List 1 Accent 2\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"66\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Medium List 2 Accent 2\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"67\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Medium Grid 1 Accent 2\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"68\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Medium Grid 2 Accent 2\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"69\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Medium Grid 3 Accent 2\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"70\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Dark List Accent 2\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"71\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Colorful Shading Accent 2\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"72\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Colorful List Accent 2\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"73\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Colorful Grid Accent 2\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"60\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Light Shading Accent 3\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"61\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Light List Accent 3\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"62\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Light Grid Accent 3\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"63\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Medium Shading 1 Accent 3\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"64\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Medium Shading 2 Accent 3\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"65\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Medium List 1 Accent 3\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"66\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Medium List 2 Accent 3\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"67\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Medium Grid 1 Accent 3\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"68\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Medium Grid 2 Accent 3\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"69\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Medium Grid 3 Accent 3\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"70\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Dark List Accent 3\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"71\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Colorful Shading Accent 3\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"72\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Colorful List Accent 3\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"73\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Colorful Grid Accent 3\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"60\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Light Shading Accent 4\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"61\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Light List Accent 4\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"62\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Light Grid Accent 4\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"63\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Medium Shading 1 Accent 4\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"64\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Medium Shading 2 Accent 4\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"65\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Medium List 1 Accent 4\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"66\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Medium List 2 Accent 4\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"67\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Medium Grid 1 Accent 4\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"68\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Medium Grid 2 Accent 4\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"69\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Medium Grid 3 Accent 4\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"70\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Dark List Accent 4\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"71\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Colorful Shading Accent 4\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"72\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Colorful List Accent 4\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"73\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Colorful Grid Accent 4\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"60\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Light Shading Accent 5\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"61\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Light List Accent 5\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"62\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Light Grid Accent 5\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"63\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Medium Shading 1 Accent 5\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"64\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Medium Shading 2 Accent 5\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"65\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Medium List 1 Accent 5\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"66\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Medium List 2 Accent 5\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"67\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Medium Grid 1 Accent 5\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"68\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Medium Grid 2 Accent 5\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"69\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Medium Grid 3 Accent 5\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"70\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Dark List Accent 5\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"71\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Colorful Shading Accent 5\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"72\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Colorful List Accent 5\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"73\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Colorful Grid Accent 5\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"60\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Light Shading Accent 6\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"61\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Light List Accent 6\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"62\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Light Grid Accent 6\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"63\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Medium Shading 1 Accent 6\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"64\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Medium Shading 2 Accent 6\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"65\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Medium List 1 Accent 6\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"66\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Medium List 2 Accent 6\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"67\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Medium Grid 1 Accent 6\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"68\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Medium Grid 2 Accent 6\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"69\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Medium Grid 3 Accent 6\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"70\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Dark List Accent 6\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"71\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Colorful Shading Accent 6\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"72\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Colorful List Accent 6\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"73\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" Name=\"Colorful Grid Accent 6\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"19\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" QFormat=\"true\" Name=\"Subtle Emphasis\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"21\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" QFormat=\"true\" Name=\"Intense Emphasis\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"31\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" QFormat=\"true\" Name=\"Subtle Reference\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"32\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" QFormat=\"true\" Name=\"Intense Reference\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"33\" SemiHidden=\"false\"", bw);
		write("   UnhideWhenUsed=\"false\" QFormat=\"true\" Name=\"Book Title\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"37\" Name=\"Bibliography\"/>", bw);
		write("  <w:LsdException Locked=\"false\" Priority=\"39\" QFormat=\"true\" Name=\"TOC Heading\"/>", bw);
		write(" </w:LatentStyles>", bw);
		write("</xml><![endif]-->", bw);
		write("<style>", bw);
		write("<!--", bw);
		write(" /* Font Definitions */", bw);
		write(" @font-face", bw);
		write("	{font-family:Tahoma;", bw);
		write("	panose-1:2 11 6 4 3 5 4 4 2 4;", bw);
		write("	mso-font-charset:0;", bw);
		write("	mso-generic-font-family:swiss;", bw);
		write("	mso-font-format:other;", bw);
		write("	mso-font-pitch:variable;", bw);
		write("	mso-font-signature:3 0 0 0 1 0;}", bw);
		write(" /* Style Definitions */", bw);
		write(" p.MsoNormal, li.MsoNormal, div.MsoNormal", bw);
		write("	{mso-style-unhide:no;", bw);
		write("	mso-style-qformat:yes;", bw);
		write("	mso-style-parent:\"\";", bw);
		write("	margin:0in;", bw);
		write("	margin-bottom:.0001pt;", bw);
		write("	mso-pagination:widow-orphan;", bw);
		write("	font-size:12.0pt;", bw);
		write("	font-family:\"Times New Roman\",\"serif\";", bw);
		write("	mso-fareast-font-family:\"Times New Roman\";}", bw);
		write("a:link, span.MsoHyperlink", bw);
		write("	{mso-style-noshow:yes;", bw);
		write("	mso-ansi-font-size:8.0pt;", bw);
		write("	mso-bidi-font-size:8.0pt;", bw);
		write("	font-family:\"Arial\",\"sans-serif\";", bw);
		write("	mso-ascii-font-family:Arial;", bw);
		write("	mso-hansi-font-family:Arial;", bw);
		write("	mso-bidi-font-family:Arial;", bw);
		write("	color:#FFC600;", bw);
		write("	mso-text-animation:none;", bw);
		write("	font-weight:bold;", bw);
		write("	text-decoration:none;", bw);
		write("	text-underline:none;", bw);
		write("	text-decoration:none;", bw);
		write("	text-line-through:none;}", bw);
		write("a:visited, span.MsoHyperlinkFollowed", bw);
		write("	{mso-style-noshow:yes;", bw);
		write("	mso-style-priority:99;", bw);
		write("	color:purple;", bw);
		write("	mso-themecolor:followedhyperlink;", bw);
		write("	text-decoration:underline;", bw);
		write("	text-underline:single;}", bw);
		write("pre", bw);
		write("	{mso-style-link:\"HTML Preformatted Char\";", bw);
		write("	margin:0in;", bw);
		write("	margin-bottom:.0001pt;", bw);
		write("	mso-pagination:widow-orphan;", bw);
		write("	font-size:10.0pt;", bw);
		write("	font-family:\"Courier New\";", bw);
		write("	mso-fareast-font-family:\"Times New Roman\";}", bw);
		write("p.MsoAcetate, li.MsoAcetate, div.MsoAcetate", bw);
		write("	{mso-style-noshow:yes;", bw);
		write("	mso-style-priority:99;", bw);
		write("	mso-style-link:\"Balloon Text Char\";", bw);
		write("	margin:0in;", bw);
		write("	margin-bottom:.0001pt;", bw);
		write("	mso-pagination:widow-orphan;", bw);
		write("	font-size:8.0pt;", bw);
		write("	font-family:\"Tahoma\",\"sans-serif\";", bw);
		write("	mso-fareast-font-family:\"Times New Roman\";", bw);
		write("	mso-bidi-font-family:Tahoma;}", bw);
		write("span.HTMLPreformattedChar", bw);
		write("	{mso-style-name:\"HTML Preformatted Char\";", bw);
		write("	mso-style-unhide:no;", bw);
		write("	mso-style-locked:yes;", bw);
		write("	mso-style-link:\"HTML Preformatted\";", bw);
		write("	mso-ansi-font-size:10.0pt;", bw);
		write("	mso-bidi-font-size:10.0pt;", bw);
		write("	font-family:\"Courier New\";", bw);
		write("	mso-ascii-font-family:\"Courier New\";", bw);
		write("	mso-fareast-font-family:\"Times New Roman\";", bw);
		write("	mso-hansi-font-family:\"Courier New\";", bw);
		write("	mso-bidi-font-family:\"Courier New\";}", bw);
		write("span.BalloonTextChar", bw);
		write("	{mso-style-name:\"Balloon Text Char\";", bw);
		write("	mso-style-noshow:yes;", bw);
		write("	mso-style-priority:99;", bw);
		write("	mso-style-unhide:no;", bw);
		write("	mso-style-locked:yes;", bw);
		write("	mso-style-link:\"Balloon Text\";", bw);
		write("	mso-ansi-font-size:8.0pt;", bw);
		write("	mso-bidi-font-size:8.0pt;", bw);
		write("	font-family:\"Tahoma\",\"sans-serif\";", bw);
		write("	mso-ascii-font-family:Tahoma;", bw);
		write("	mso-fareast-font-family:\"Times New Roman\";", bw);
		write("	mso-hansi-font-family:Tahoma;", bw);
		write("	mso-bidi-font-family:Tahoma;}", bw);
		write("span.SpellE", bw);
		write("	{mso-style-name:\"\";", bw);
		write("	mso-spl-e:yes;}", bw);
		write("span.GramE", bw);
		write("	{mso-style-name:\"\";", bw);
		write("	mso-gram-e:yes;}", bw);
		write(".MsoChpDefault", bw);
		write("	{mso-style-type:export-only;", bw);
		write("	mso-default-props:yes;", bw);
		write("	font-family:\"Calibri\",\"sans-serif\";", bw);
		write("	mso-ascii-font-family:Calibri;", bw);
		write("	mso-ascii-theme-font:minor-latin;", bw);
		write("	mso-fareast-font-family:Calibri;", bw);
		write("	mso-fareast-theme-font:minor-latin;", bw);
		write("	mso-hansi-font-family:Calibri;", bw);
		write("	mso-hansi-theme-font:minor-latin;", bw);
		write("	mso-bidi-font-family:\"Times New Roman\";", bw);
		write("	mso-bidi-theme-font:minor-bidi;}", bw);
		write(".MsoPapDefault", bw);
		write("	{mso-style-type:export-only;", bw);
		write("	margin-bottom:10.0pt;", bw);
		write("	line-height:115%;}", bw);
		write("@page WordSection1", bw);
		write("	{size:8.5in 11.0in;", bw);
		write("	margin:.5in .5in .5in .5in;", bw);
		write("	mso-header-margin:.5in;", bw);
		write("	mso-footer-margin:.5in;", bw);
		write("	mso-paper-source:0;}", bw);
		write("div.WordSection1", bw);
		write("	{page:WordSection1;}", bw);
		write("-->", bw);
		write("</style>", bw);
		write("<!--[if gte mso 10]>", bw);
		write("<style>", bw);
		write(" /* Style Definitions */", bw);
		write(" table.MsoNormalTable", bw);
		write("	{mso-style-name:\"Table Normal\";", bw);
		write("	mso-tstyle-rowband-size:0;", bw);
		write("	mso-tstyle-colband-size:0;", bw);
		write("	mso-style-noshow:yes;", bw);
		write("	mso-style-priority:99;", bw);
		write("	mso-style-parent:\"\";", bw);
		write("	mso-padding-alt:0in 5.4pt 0in 5.4pt;", bw);
		write("	mso-para-margin-top:0in;", bw);
		write("	mso-para-margin-right:0in;", bw);
		write("	mso-para-margin-bottom:10.0pt;", bw);
		write("	mso-para-margin-left:0in;", bw);
		write("	line-height:115%;", bw);
		write("	mso-pagination:widow-orphan;", bw);
		write("	font-size:11.0pt;", bw);
		write("	font-family:\"Calibri\",\"sans-serif\";", bw);
		write("	mso-ascii-font-family:Calibri;", bw);
		write("	mso-ascii-theme-font:minor-latin;", bw);
		write("	mso-hansi-font-family:Calibri;", bw);
		write("	mso-hansi-theme-font:minor-latin;", bw);
		write("	mso-bidi-font-family:\"Times New Roman\";", bw);
		write("	mso-bidi-theme-font:minor-bidi;}", bw);
		write("table.MsoTableGrid", bw);
		write("	{mso-style-name:\"Table Grid\";", bw);
		write("	mso-tstyle-rowband-size:0;", bw);
		write("	mso-tstyle-colband-size:0;", bw);
		write("	mso-style-unhide:no;", bw);
		write("	border:solid windowtext 1.0pt;", bw);
		write("	mso-border-alt:solid windowtext .5pt;", bw);
		write("	mso-padding-alt:0in 5.4pt 0in 5.4pt;", bw);
		write("	mso-border-insideh:.5pt solid windowtext;", bw);
		write("	mso-border-insidev:.5pt solid windowtext;", bw);
		write("	mso-para-margin:0in;", bw);
		write("	mso-para-margin-bottom:.0001pt;", bw);
		write("	mso-pagination:widow-orphan;", bw);
		write("	font-size:10.0pt;", bw);
		write("	font-family:\"Times New Roman\",\"serif\";", bw);
		write("	mso-fareast-font-family:\"Times New Roman\";}", bw);
		write("</style>", bw);
		write("<![endif]--><!--[if gte mso 9]><xml>", bw);
		write(" <o:shapedefaults v:ext=\"edit\" spidmax=\"1026\"/>", bw);
		write("</xml><![endif]--><!--[if gte mso 9]><xml>", bw);
		write(" <o:shapelayout v:ext=\"edit\">", bw);
		write("  <o:idmap v:ext=\"edit\" data=\"1\"/>", bw);
		write(" </o:shapelayout></xml><![endif]-->", bw);
		write("</head>", bw);
		write("", bw);
		write("<body lang=EN-US link=\"#FFC600\" vlink=purple style='tab-interval:.5in'>", bw);
		write("", bw);
		write("<div class=WordSection1>", bw);
		write("", bw);
		write("<table class=MsoTableGrid border=0 cellspacing=0 cellpadding=0", bw);
		write(" style='border-collapse:collapse;border:none;mso-yfti-tbllook:1567;mso-padding-alt:", bw);
		write(" 0in 5.4pt 0in 5.4pt;mso-border-insideh:none;mso-border-insidev:none'>", bw);
		write(" <tr style='mso-yfti-irow:0;mso-yfti-firstrow:yes'>", bw);
		write("  <td width=361 valign=top style='width:270.65pt;padding:0in 5.4pt 0in 5.4pt'><pre><span", bw);
		write("  class=SpellE><b><span style='font-size:8.0pt'>" + fakeSheet.getSongName() + "-" + fakeSheet.getArtistName()
				+ "</span></b></span><b><spanstyle='font-size:8.0pt'> <o:p></o:p></span></b></pre>", bw);
		write("   <pre><span style='font-size:8.0pt;mso-bidi-font-weight:bold'><o:p></o:p></span></pre>", bw);

		// Lyrics
		textArray = fakeSheet.getTextArea().getTextAreaArray();
		for (int i = 0; i < textArray.length; i++)
		{
			write("   <pre><span style='font-size:8.0pt;mso-bidi-font-weight:bold'>" + textArray[i] + "<o:p></o:p></span></pre>", bw);
		}

		write("  </td>", bw);
		write("  <td width=414 valign=top style='width:310.75pt;padding:0in 5.4pt 0in 5.4pt'>", bw);
		write("  <pre><span style='font-size:8.0pt;mso-no-proof:yes'><!--[if gte vml 1]><v:shapetype", bw);
		write("   id=\"_x0000_t75\" coordsize=\"21600,21600\" o:spt=\"75\" o:preferrelative=\"t\"", bw);
		write("   path=\"m@4@5l@4@11@9@11@9@5xe\" filled=\"f\" stroked=\"f\">", bw);
		write("   <v:stroke joinstyle=\"miter\"/>", bw);
		write("   <v:formulas>", bw);
		write("    <v:f eqn=\"if lineDrawn pixelLineWidth 0\"/>", bw);
		write("    <v:f eqn=\"sum @0 1 0\"/>", bw);
		write("    <v:f eqn=\"sum 0 0 @1\"/>", bw);
		write("    <v:f eqn=\"prod @2 1 2\"/>", bw);
		write("    <v:f eqn=\"prod @3 21600 pixelWidth\"/>", bw);
		write("    <v:f eqn=\"prod @3 21600 pixelHeight\"/>", bw);
		write("    <v:f eqn=\"sum @0 0 1\"/>", bw);
		write("    <v:f eqn=\"prod @6 1 2\"/>", bw);
		write("    <v:f eqn=\"prod @7 21600 pixelWidth\"/>", bw);
		write("    <v:f eqn=\"sum @8 21600 0\"/>", bw);
		write("    <v:f eqn=\"prod @7 21600 pixelHeight\"/>", bw);
		write("    <v:f eqn=\"sum @10 21600 0\"/>", bw);
		write("   </v:formulas>", bw);
		write("   <v:path o:extrusionok=\"f\" gradientshapeok=\"t\" o:connecttype=\"rect\"/>", bw);
		write("   <o:lock v:ext=\"edit\" aspectratio=\"t\"/>", bw);
		write("  </v:shapetype><![endif]-->", bw);

		// Images
		chordCharts = fakeSheet.getChordChartArea().getChordChartArea();
		(new File(fileDirectory)).mkdir();
		int chartId = 0;
		for (Vector<GuitarChordChart> chartRow : chordCharts)
		{
			write("<pre><span style='font-size:8.0pt;mso-no-proof:yes'>", bw);
			for (GuitarChordChart chart : chartRow)
			{
				chartId++;
				chart.writeImageToFile(fileDirectory + "/chart" + Integer.toString(chartId) + ".jpg");
				bw.write(" <img width=66 height=72 src=\"./" + fileLocalPath + "/chart" + Integer.toString(chartId) + ".jpg\">");
			}
			write("</span></pre>", bw);
		}

		/*
		 * write(" <![if !vml]><img width=66 height=72 src=\"Layla_files/image002.jpg\" v:shapes=\"_x0000_i1047\"><![endif]><!--[if gte vml 1]><v:shape"
		 * ,bw); write("   id=\"_x0000_i1046\" type=\"#_x0000_t75\" style='width:49.5pt;height:54pt;",bw);
		 * write("   visibility:visible;mso-wrap-style:square'>",bw); write("   <v:imagedata src=\"Layla_files/image003.png\" o:title=\"\"/>",bw);
		 * write("  </v:shape><![endif]--><![if !vml]>",bw);
		 * 
		 * write("  <img width=66 height=72 src=\"Layla_files/image004.jpg\" v:shapes=\"_x0000_i1046\"><![endif]><!--[if gte vml 1]><v:shape",bw);
		 * write("   id=\"_x0000_i1045\" type=\"#_x0000_t75\" style='width:49.5pt;height:54pt;",bw);
		 * write("   visibility:visible;mso-wrap-style:square'>",bw); write("   <v:imagedata src=\"Layla_files/image005.png\" o:title=\"\"/>",bw);
		 * write("  </v:shape><![endif]--><![if !vml]>",bw);
		 * 
		 * write("  <img width=66 height=72",bw);
		 * write("  src=\"Layla_files/image006.jpg\" v:shapes=\"_x0000_i1045\"><![endif]><!--[if gte vml 1]><v:shape",bw);
		 * write("   id=\"_x0000_i1044\" type=\"#_x0000_t75\" style='width:49.5pt;height:54pt;",bw);
		 * write("   visibility:visible;mso-wrap-style:square'>",bw); write("   <v:imagedata src=\"Layla_files/image001.png\" o:title=\"\"/>",bw);
		 * write("  </v:shape><![endif]--><![if !vml]><img width=66 height=72",bw);
		 * write("  src=\"Layla_files/image002.jpg\" v:shapes=\"_x0000_i1044\"><![endif]></span><span",bw);
		 * write("  style='font-size:8.0pt;mso-bidi-font-weight:bold'><o:p></o:p></span></pre><pre><span",bw);
		 * write("  style='font-size:8.0pt;mso-bidi-font-weight:bold'><o:p>&nbsp;</o:p></span></pre><pre><span",bw);
		 * write("  style='font-size:8.0pt;mso-bidi-font-weight:bold'><o:p>&nbsp;</o:p></span></pre><pre><span",bw);
		 * write("  style='font-size:8.0pt;mso-bidi-font-weight:bold'>Verse<o:p></o:p></span></pre><pre><span",bw);
		 * write("  style='font-size:8.0pt;mso-no-proof:yes'><!--[if gte vml 1]><v:shape id=\"_x0000_i1043\"",bw);
		 * write("   type=\"#_x0000_t75\" style='width:49.5pt;height:54pt;visibility:visible;",bw); write("   mso-wrap-style:square'>",bw);
		 * write("   <v:imagedata src=\"Layla_files/image007.png\" o:title=\"\"/>",bw);
		 * write("  </v:shape><![endif]--><![if !vml]><img width=66 height=72",bw);
		 * write("  src=\"Layla_files/image008.jpg\" v:shapes=\"_x0000_i1043\"><![endif]><!--[if gte vml 1]><v:shape",bw);
		 * write("   id=\"Picture_x0020_2963\" o:spid=\"_x0000_i1042\" type=\"#_x0000_t75\" style='width:49.5pt;",bw);
		 * write("   height:54pt;visibility:visible;mso-wrap-style:square'>",bw);
		 * write("   <v:imagedata src=\"Layla_files/image009.png\" o:title=\"\"/>",bw);
		 * write("  </v:shape><![endif]--><![if !vml]><img width=66 height=72",bw);
		 * write("  src=\"Layla_files/image010.jpg\" v:shapes=\"Picture_x0020_2963\"><![endif]></span><span",bw);
		 * write("  style='font-size:8.0pt;mso-bidi-font-weight:bold'><o:p></o:p></span></pre><pre><span",bw);
		 * write("  style='font-size:8.0pt;mso-bidi-font-weight:bold'><o:p>&nbsp;</o:p></span></pre><pre><span",bw);
		 * write("  style='font-size:8.0pt;mso-no-proof:yes'><!--[if gte vml 1]><v:shape id=\"Picture_x0020_2966\"",bw);
		 * write("   o:spid=\"_x0000_i1041\" type=\"#_x0000_t75\" style='width:49.5pt;height:54pt;",bw);
		 * write("   visibility:visible;mso-wrap-style:square'>",bw); write("   <v:imagedata src=\"Layla_files/image007.png\" o:title=\"\"/>",bw);
		 * write("  </v:shape><![endif]--><![if !vml]><img width=66 height=72",bw);
		 * write("  src=\"Layla_files/image008.jpg\" v:shapes=\"Picture_x0020_2966\"><![endif]><!--[if gte vml 1]><v:shape",bw);
		 * write("   id=\"Picture_x0020_2999\" o:spid=\"_x0000_i1040\" type=\"#_x0000_t75\" style='width:49.5pt;",bw);
		 * write("   height:54pt;visibility:visible;mso-wrap-style:square'>",bw);
		 * write("   <v:imagedata src=\"Layla_files/image005.png\" o:title=\"\"/>",bw);
		 * write("  </v:shape><![endif]--><![if !vml]><img width=66 height=72",bw);
		 * write("  src=\"Layla_files/image006.jpg\" v:shapes=\"Picture_x0020_2999\"><![endif]><!--[if gte vml 1]><v:shape",bw);
		 * write("   id=\"Picture_x0020_2972\" o:spid=\"_x0000_i1039\" type=\"#_x0000_t75\" style='width:49.5pt;",bw);
		 * write("   height:54pt;visibility:visible;mso-wrap-style:square'>",bw);
		 * write("   <v:imagedata src=\"Layla_files/image011.png\" o:title=\"\"/>",bw);
		 * write("  </v:shape><![endif]--><![if !vml]><img width=66 height=72",bw);
		 * write("  src=\"Layla_files/image012.jpg\" v:shapes=\"Picture_x0020_2972\"><![endif]><!--[if gte vml 1]><v:shape",bw);
		 * write("   id=\"_x0000_i1038\" type=\"#_x0000_t75\" style='width:49.5pt;height:54pt;",bw);
		 * write("   visibility:visible;mso-wrap-style:square'>",bw); write("   <v:imagedata src=\"Layla_files/image013.png\" o:title=\"\"/>",bw);
		 * write("  </v:shape><![endif]--><![if !vml]><img width=66 height=72",bw);
		 * write("  src=\"Layla_files/image014.jpg\" v:shapes=\"_x0000_i1038\"><![endif]><!--[if gte vml 1]><v:shape",bw);
		 * write("   id=\"Picture_x0020_2978\" o:spid=\"_x0000_i1037\" type=\"#_x0000_t75\" style='width:49.5pt;",bw);
		 * write("   height:54pt;visibility:visible;mso-wrap-style:square'>",bw);
		 * write("   <v:imagedata src=\"Layla_files/image015.png\" o:title=\"\"/>",bw);
		 * write("  </v:shape><![endif]--><![if !vml]><img width=66 height=72",bw);
		 * write("  src=\"Layla_files/image016.jpg\" v:shapes=\"Picture_x0020_2978\"><![endif]></span><span",bw);
		 * write("  style='font-size:8.0pt;mso-bidi-font-weight:bold'><o:p></o:p></span></pre><pre><span",bw);
		 * write("  style='font-size:8.0pt;mso-no-proof:yes'><!--[if gte vml 1]><v:shape id=\"_x0000_i1036\"",bw);
		 * write("   type=\"#_x0000_t75\" style='width:49.5pt;height:54pt;visibility:visible;",bw); write("   mso-wrap-style:square'>",bw);
		 * write("   <v:imagedata src=\"Layla_files/image017.png\" o:title=\"\"/>",bw);
		 * write("  </v:shape><![endif]--><![if !vml]><img width=66 height=72",bw);
		 * write("  src=\"Layla_files/image018.jpg\" v:shapes=\"_x0000_i1036\"><![endif]><!--[if gte vml 1]><v:shape",bw);
		 * write("   id=\"_x0000_i1035\" type=\"#_x0000_t75\" style='width:49.5pt;height:54pt;",bw);
		 * write("   visibility:visible;mso-wrap-style:square'>",bw); write("   <v:imagedata src=\"Layla_files/image019.png\" o:title=\"\"/>",bw);
		 * write("  </v:shape><![endif]--><![if !vml]><img width=66 height=72",bw);
		 * write("  src=\"Layla_files/image020.jpg\" v:shapes=\"_x0000_i1035\"><![endif]><!--[if gte vml 1]><v:shape",bw);
		 * write("   id=\"_x0000_i1034\" type=\"#_x0000_t75\" style='width:49.5pt;height:54pt;",bw);
		 * write("   visibility:visible;mso-wrap-style:square'>",bw); write("   <v:imagedata src=\"Layla_files/image013.png\" o:title=\"\"/>",bw);
		 * write("  </v:shape><![endif]--><![if !vml]><img width=66 height=72",bw);
		 * write("  src=\"Layla_files/image014.jpg\" v:shapes=\"_x0000_i1034\"><![endif]><!--[if gte vml 1]><v:shape",bw);
		 * write("   id=\"_x0000_i1033\" type=\"#_x0000_t75\" style='width:49.5pt;height:54pt;",bw);
		 * write("   visibility:visible;mso-wrap-style:square'>",bw); write("   <v:imagedata src=\"Layla_files/image021.png\" o:title=\"\"/>",bw);
		 * write("  </v:shape><![endif]--><![if !vml]><img width=66 height=72",bw);
		 * write("  src=\"Layla_files/image022.jpg\" v:shapes=\"_x0000_i1033\"><![endif]></span><span",bw);
		 * write("  style='font-size:8.0pt;mso-bidi-font-weight:bold'><o:p></o:p></span></pre><pre><span",bw);
		 * write("  style='font-size:8.0pt;mso-no-proof:yes'><!--[if gte vml 1]><v:shape id=\"Picture_x0020_2981\"",bw);
		 * write("   o:spid=\"_x0000_i1032\" type=\"#_x0000_t75\" style='width:49.5pt;height:54pt;",bw);
		 * write("   visibility:visible;mso-wrap-style:square'>",bw); write("   <v:imagedata src=\"Layla_files/image017.png\" o:title=\"\"/>",bw);
		 * write("  </v:shape><![endif]--><![if !vml]><img width=66 height=72",bw);
		 * write("  src=\"Layla_files/image018.jpg\" v:shapes=\"Picture_x0020_2981\"><![endif]><!--[if gte vml 1]><v:shape",bw);
		 * write("   id=\"Picture_x0020_2984\" o:spid=\"_x0000_i1031\" type=\"#_x0000_t75\" style='width:49.5pt;",bw);
		 * write("   height:54pt;visibility:visible;mso-wrap-style:square'>",bw);
		 * write("   <v:imagedata src=\"Layla_files/image019.png\" o:title=\"\"/>",bw);
		 * write("  </v:shape><![endif]--><![if !vml]><img width=66 height=72",bw);
		 * write("  src=\"Layla_files/image020.jpg\" v:shapes=\"Picture_x0020_2984\"><![endif]><!--[if gte vml 1]><v:shape",bw);
		 * write("   id=\"Picture_x0020_2975\" o:spid=\"_x0000_i1030\" type=\"#_x0000_t75\" style='width:49.5pt;",bw);
		 * write("   height:54pt;visibility:visible;mso-wrap-style:square'>",bw);
		 * write("   <v:imagedata src=\"Layla_files/image013.png\" o:title=\"\"/>",bw);
		 * write("  </v:shape><![endif]--><![if !vml]><img width=66 height=72",bw);
		 * write("  src=\"Layla_files/image014.jpg\" v:shapes=\"Picture_x0020_2975\"><![endif]><!--[if gte vml 1]><v:shape",bw);
		 * write("   id=\"Picture_x0020_2987\" o:spid=\"_x0000_i1029\" type=\"#_x0000_t75\" style='width:49.5pt;",bw);
		 * write("   height:54pt;visibility:visible;mso-wrap-style:square'>",bw);
		 * write("   <v:imagedata src=\"Layla_files/image021.png\" o:title=\"\"/>",bw);
		 * write("  </v:shape><![endif]--><![if !vml]><img width=66 height=72",bw);
		 * write("  src=\"Layla_files/image022.jpg\" v:shapes=\"Picture_x0020_2987\"><![endif]></span><span",bw);
		 * write("  style='font-size:8.0pt;mso-bidi-font-weight:bold'><o:p></o:p></span></pre><pre><span",bw);
		 * write("  style='font-size:8.0pt;mso-bidi-font-weight:bold'><o:p>&nbsp;</o:p></span></pre><pre><span",bw);
		 * write("  style='font-size:8.0pt;mso-bidi-font-weight:bold'><o:p>&nbsp;</o:p></span></pre><pre><span",bw);
		 * write("  style='font-size:8.0pt;mso-bidi-font-weight:bold'>Chorus<o:p></o:p></span></pre><pre><span",bw);
		 * write("  style='font-size:8.0pt;mso-no-proof:yes'><!--[if gte vml 1]><v:shape id=\"_x0000_i1028\"",bw);
		 * write("   type=\"#_x0000_t75\" style='width:49.5pt;height:54pt;visibility:visible;",bw); write("   mso-wrap-style:square'>",bw);
		 * write("   <v:imagedata src=\"Layla_files/image001.png\" o:title=\"\"/>",bw);
		 * write("  </v:shape><![endif]--><![if !vml]><img width=66 height=72",bw);
		 * write("  src=\"Layla_files/image002.jpg\" v:shapes=\"_x0000_i1028\"><![endif]><!--[if gte vml 1]><v:shape",bw);
		 * write("   id=\"Picture_x0020_2993\" o:spid=\"_x0000_i1027\" type=\"#_x0000_t75\" style='width:49.5pt;",bw);
		 * write("   height:54pt;visibility:visible;mso-wrap-style:square'>",bw);
		 * write("   <v:imagedata src=\"Layla_files/image003.png\" o:title=\"\"/>",bw);
		 * write("  </v:shape><![endif]--><![if !vml]><img width=66 height=72",bw);
		 * write("  src=\"Layla_files/image004.jpg\" v:shapes=\"Picture_x0020_2993\"><![endif]><!--[if gte vml 1]><v:shape",bw);
		 * write("   id=\"Picture_x0020_3002\" o:spid=\"_x0000_i1026\" type=\"#_x0000_t75\" style='width:49.5pt;",bw);
		 * write("   height:54pt;visibility:visible;mso-wrap-style:square'>",bw);
		 * write("   <v:imagedata src=\"Layla_files/image005.png\" o:title=\"\"/>",bw);
		 * write("  </v:shape><![endif]--><![if !vml]><img width=66 height=72",bw);
		 * write("  src=\"Layla_files/image006.jpg\" v:shapes=\"Picture_x0020_3002\"><![endif]><!--[if gte vml 1]><v:shape",bw);
		 * write("   id=\"Picture_x0020_2990\" o:spid=\"_x0000_i1025\" type=\"#_x0000_t75\" style='width:49.5pt;",bw);
		 * write("   height:54pt;visibility:visible;mso-wrap-style:square'>",bw);
		 * write("   <v:imagedata src=\"Layla_files/image001.png\" o:title=\"\"/>",bw);
		 * write("  </v:shape><![endif]--><![if !vml]><img width=66 height=72",bw);
		 * write("  src=\"Layla_files/image002.jpg\" v:shapes=\"Picture_x0020_2990\"><![endif]></span><span",bw);
		 * write("  style='font-size:8.0pt;mso-bidi-font-weight:bold'><o:p></o:p></span></pre><pre><span",bw);
		 * write("  style='font-size:8.0pt;mso-bidi-font-weight:bold'><o:p>&nbsp;</o:p></span></pre><pre><span",bw);
		 * write("  style='font-size:8.0pt;mso-bidi-font-weight:bold'><o:p>&nbsp;</o:p></span></pre><pre><span",bw);
		 * write("  style='font-size:8.0pt;mso-bidi-font-weight:bold'><o:p>&nbsp;</o:p></span></pre></td>",bw);
		 */
		write(" </tr>", bw);
		write(" <tr style='mso-yfti-irow:1;mso-yfti-lastrow:yes'>", bw);
		write("  <td width=361 valign=top style='width:270.65pt;padding:0in 5.4pt 0in 5.4pt'><pre><span", bw);
		write("  style='font-size:8.0pt;mso-bidi-font-weight:bold'><o:p>&nbsp;</o:p></span></pre></td>", bw);
		write("  <td width=414 valign=top style='width:310.75pt;padding:0in 5.4pt 0in 5.4pt'><pre><span", bw);
		write("  style='font-size:8.0pt;mso-bidi-font-weight:bold'><o:p>&nbsp;</o:p></span></pre></td>", bw);
		write(" </tr>", bw);
		write("</table>", bw);
		write("", bw);
		write("<pre><span style='font-size:8.0pt;mso-bidi-font-weight:bold'><o:p>&nbsp;</o:p></span></pre>", bw);
		write("", bw);
		write("<p class=MsoNormal><span style='font-size:8.0pt'><o:p>&nbsp;</o:p></span></p>", bw);
		write("", bw);
		write("</div>", bw);
		write("", bw);
		write("</body>", bw);
		write("", bw);
		write("</html>", bw);

		bw.close();
		return;
	}

	private void write(String line, BufferedWriter bw)
	{
		try
		{
			bw.write(line);
		} catch (IOException e)
		{
			e.printStackTrace();
		}
		try
		{
			bw.newLine();
		} catch (IOException e)
		{
			e.printStackTrace();
		}
	}
}
